version: '3.4'

services:
  mssql:
    image: masstransit/sqlserver-quartz:latest
    ports:
      - 1433:1433
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"

  rabbitmq:
    container_name: "rabbitmqcontainer"
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
        - '5672:5672'
        - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - "./rabbitmq/:/var/lib/rabbitmq"
    

  masstransitdemo.api:
    image: ${DOCKER_REGISTRY-}masstransitdemoapi
    build:
      context: .
      dockerfile: MasstransitDemo.Api/Dockerfile
    ports:
        - '7047:443'
        - '7048:80'     
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masstransit.consumer:
    image: ${DOCKER_REGISTRY-}masstransitconsumer
    build:
      context: .
      dockerfile: MasstransitDemo.Consumer/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy